### ISSUE TITLE
Distinguish between motorized and ultralight traffic circuit types

### ISSUE THREAD

**Issue by mipastgt** [openAIP/openaip-public#8]
I just had a look at the schema definition for Airports and I was a bit astonished to see that Airport\Runway\TrafficCircuit\Type only offers a distinction between glider and powered. At least in germany it is very common that airfields also have distinct traffic circuits for motorized and ultralight traffic, which can be substantially different. It would be nice if such a ultralight category could be added. As an example see attached screen shot. Guess which one is the the ultralight circuit :-)
<img width="428" alt="bildschirmfoto 2018-05-31 um 12 18 32" src="https://user-images.githubusercontent.com/16735714/40777142-3e55ff5a-64cd-11e8-8a36-d55ebf44537b.png">
<img width="685" alt="bildschirmfoto 2018-05-31 um 12 24 41" src="https://user-images.githubusercontent.com/16735714/40777275-b900ea4e-64cd-11e8-9d30-8b28afe501f9.png">

**Comment by reskume** [comment]
Yes, good point. 👍 Will be added asap.
