### ISSUE TITLE
Available Countries

### ISSUE THREAD

**Issue by jannikscho** [openAIP/openaip-public#9]
I would like to check the available countries and then load the data for these countries.
At the moment every country has to be requested and then the error code has to be evaluated.

As an an example:
An endpoint for existing countries would enough:
/countries

Optimal would be 1 endpoint per data basis:
/airports/countries
/airspaces/countries
/navaids/countries

and so on ..

**Comment by reskume** [comment]
Yep, good point.  I'll implement it and ship it with the next version. Could take while - currently the frontend is being refactored.

**Comment by reskume** [comment]
Fixed with next release.
